<div class="ad-options">
	<div class="classified-ad-option">
		<div class="classified-types">
			<h3>Classified Ad</h3>
			<div class="classified-new">
				<div class="classified-title">
					<p>New :</p>
				</div>
				<div class="classified-expiry">
					<p>3 Months</p>
					<p>6 Months</p>
					<p>12 Months</p>
				</div>
			</div>
			<div class="classified-used">
				<div class="classified-title">
					<p>Used :</p>
				</div>
				<div class="classified-expiry">
					<p>3 Months</p>
				</div>
			</div>
			<div class="classified-rental">
				<div class="classified-title">
					<p>Rental :</p>
				</div>
				<div class="classified-expiry">
					<p>3 Months</p>
					<p>6 Months</p>
				</div>
			</div>
			<div class="classified-spare">
				<div class="classified-title">
					<p>Spare :</p>
				</div>
				<div class="classified-expiry">
					<p>3 Months</p>
					<p>6 Months</p>
					<p>12 Months</p>
				</div>
			</div>
		</div>
		<div class="classified-ad-option-booknow">
			<button style="cursor:pointer" onclick="setLocation('<?php echo Mage::getUrl('postad/index/classifiedad')?>')" type="button" name="book-now" class="book-now-button">Book Now </button>
		</div>	
	</div>
	<div class="banner-ad-options">
		<h3>Banner Ad</h3>
		<div class="banner-top">
			<div class="banner-title">
				<p>Top Part Of The Webiste :</p>
			</div>
			<div class="banner-expiry">
				<p>3 Months</p>
				<p>6 Months</p>
				<p>12 Months</p>
			</div>
		</div>
		<div class="banner-side-right">
			<div class="banner-title">
				<p>Right Side Of The Webiste :</p>
			</div>
			<div class="banner-expiry">
				<p>3 Months</p>
				<p>6 Months</p>
				<p>12 Months</p>
			</div>
		</div>
		<div class="banner-side-left">
			<div class="banner-title">
				<p>Left Side Of The Webiste :</p>
			</div>
			<div class="banner-expiry">
				<p>3 Months</p>
				<p>6 Months</p>
				<p>12 Months</p>
			</div>
		</div>
		<div class="banner-bottom">
			<div class="banner-title">
				<p>Bottom Part Of The Webiste :</p>
			</div>
			<div class="banner-expiry">
				<p>3 Months</p>
				<p>6 Months</p>
				<p>12 Months</p>
			</div>
		</div>

		<div class="banner-ad-option-contact">
			<button style="cursor:pointer" type="button" name="contact" onclick="setLocation('<?php echo Mage::getUrl('postad/index/contact')?>')" class="contact-button">Contact Us</button>
		</div>	
	</div>
</div>