<?php
	$freeTrial = Mage::app()->getRequest()->getParam('type');

?>
<div id="classfiedform">
	<form action="<?php echo $this->getClassifiedSaveUrl();?>" method="post" id="classified-ad-form" name="classified-ad-form" enctype="multipart/form-data">
		
		<h3>Classified Ad Form</h3>
		<input type="hidden" name="classifiedtype" value="<?php echo $freeTrial?>" id="trialperiod" />
		<p>
			<label for="type_of_ad" name="type_of_ad_label" id="type_of_ad_label">Type Of Ad</label>
			<select id="type_of_ad" name="type_of_ad" class="validate-select" onchange="valueCheck()">
				<option value="">Choose</option>
				<option value="6">New</option>
				<option value="5">Pre-Owned</option>
				<option value="4">Rental</option>
				<option value="3">Spare Parts</option>
			</select>

			<div class="validation-month-div">
				<div id="expiry_months_3_div" style="display:none"><input type="radio" name="expiry_months" value="3" id="expiry_months_3" checked="checked"/> <label for="expiry_months_3" id="expiry_months_3_label">3 Month Validity</label></div>

				<div id="expiry_months_6_div" style="display:none"><input type="radio" name="expiry_months" value="6" id="expiry_months_6"/> <label for="expiry_months_6" id="expiry_months_6_label">6 Month Validity</label></div>

				<div id="expiry_months_12_div" style="display:none"><input type="radio" name="expiry_months" value="12" id="expiry_months_12" /> <label for="expiry_months_12" id="expiry_months_12_label">12 Month Validity</label></div>
			</div>
		</p>

		<p>
			<label for="category" name="category_label" id="category_label">Category</label>
			<select name="category" id="category" class="validate-select" onchange="subcategorySelect();">
				<option value="">Choose</option>

				<?php foreach ( Mage::helper('catalog/category')->getStoreCategories() as $_category) { ?>
					<?php if($_category->getIsActive()){ ?>
						<option value="<?php echo $_category->getId(); ?>"><?php echo $_category->getName();?></option>
					<?php } ?>
				<?php } ?>
				<!-- <option value="other_main">Other</option> -->
			</select>
		</p>

		<!-- <p id="category_other_p" style="display:none">
			<label for="category_other" name="category_other_label" id="category_other_label">Please Enter The Category</label>
			<input name="category_other" type="text" class="required-entry" id="category_other" value=""/>
		</p> -->

		<p id="subcategory_p" style="display:none">
			<label for="sub_category" name="sub_category_label" id="sub_category_label">Sub Category</label>
			<select name="sub_category" id="sub_category"  class="validate-select" onchange="subCategoryOtherSelect()">
				<option value="0">Choose</option>
			</select> (Click  Other to add New Sub-Category )
		</p>

		<p id="subcategory_other_p" style="display:none">
			<label for="sub_category_other" name="sub_category_other_label" id="sub_category_other_label">Please Enter The Subcategory</label>
			<input name="sub_category_other" type="text" id="sub_category_other" value=""/>
		</p>

		<p>
			<label for="name" id="name_label" name="name_label">Company Name</label>
			<input name="name" id="name" value="" type="text" class="required-entry"/>
		</p>

		<p>
			<label for="description" id="description_label" name="description_label">Description</label>
			<textarea id="description" cols="25" rows="5" maxlength="500" name="description" class="required-entry"></textarea>
			<br />
			<span class="small-comment">(Please Enter The Description Of Your Company In 500 Words )</span>
		</p>

		<p id="make_p">
			<label for="make" name="make_label" id="make_label">Make</label>
			<select id="make" name="make" class="validate-select" onchange="makeSelectAction()">
				<option value="" id="make_default" name="make_default">Choose</option>

				<?php foreach (Mage::helper('postad')->getAttributeOptions('manufacturer') as $option) { ?>
					<option value="<?php echo $option['value'] ?>"><?php echo $option['label']?></option>
				<?php } ?>

			</select>
			<button type="button" name="new-make-button" id="new-make-button" onclick="enableNewMake()">Add Make</button>

			<div class="new-make-div" style="display:none">
				<label for="new-make" name="new-make-label" id="new-make-label">Enter Make</label>
				<input name="new-make" value="" id="new-make" type="text" class=""/>
			</div>
		</p>

		<p id="model_p">
			<label for="model" id="model_label" name="model_label">Model</label>
			<input type="text" id="model" cols="25" rows="5" name="model" class="required-entry" />
		</p>

		<p id="year_p">
			<label for="year" name="year_label" id="year_label">Year</label>
			<input type="text" name="year" id="year" value="" class=""/>
		</p>

		<p id="weight_p">
			<label for="weight" name="weight_label" id="weight_label">Weight(Kg)</label>
			<input type="text" name="weight" id="weight" value="" />
		</p>

		<p id="serial_num_p">
			<label for="serial_num" name="serial_num_label" id="serial_num_label">Serial Number</label>
			<input type="text" name="serial_num" id="serial_num" value="" class="" />
		</p>

		<p id="condition_p">
			<label for="condition" name="condition_label" id="condition_label">Condition</label>
			<select name="condition" id="condition" class="">
				<option value="">Choose</option>

				<?php foreach (Mage::helper('postad')->getAttributeOptions('condition') as $option) { ?>
					<option value="<?php echo $option['value'] ?>"><?php echo $option['label']?></option>
				<?php } ?>

			</select>
		</p>

		<p id="hours_p">
			<label>Hours</label>
			<input type="text" name="hours" id="hours" value="" class="" />
		</p>

		<p id="price_p">
			<label>Price INR &#8377; </label>
			<input type="text" name="ad_price" id="ad_price" value="" class="" />
		</p>
			
		</p>

		<p>
			<label ></label>
		</p>

		<p><input type="file" name="filename1" id="filename1"/>(Provide images with 'jpg','jpeg','gif','png' extensions)</p>
		<p><input type="file" name="filename2" id="filename2"/>(Provide images with 'jpg','jpeg','gif','png' extensions)</p>
		<p><input type="file" name="filename3" id="filename3"/>(Provide images with 'jpg','jpeg','gif','png' extensions)</p>
		<p><input type="file" name="filename4" id="filename4"/>(Provide images with 'jpg','jpeg','gif','png' extensions)</p>

		<p>
			<label for="country" name="country_label" id="country_label">Country</label>
			<select name="country" name="country" id="country" onchange="countrySelect()">
				
				<?php foreach (Mage::helper('postad')->getAttributeOptions('product_country') as $option) { ?>
					<option value="<?php echo $option['value'] ?>"><?php echo $option['label']?></option>
				<?php } ?>

			</select>
		</p>

		<p>
			<label>Address</label>
			<input type="text" name="address" id="address" value="" class="required-entry"/>
		</p>

		<p id="state_p">
			<label for="state" name="state_label" id="state_label">State</label>
			<select name="state" name="state" id="state" class="validate-select" onchange="addNewState()">
				<option value="">Choose</option>

				<?php foreach (Mage::helper('postad')->getAttributeOptions('product_state') as $option) { ?>
					<option value="<?php echo $option['value'] ?>"><?php echo $option['label']?></option>
				<?php } ?>
				<option value="other_state"><?php echo 'other'?></label>

			</select>(Click  Other to add State )

			<p id="add_new_state_p" style="display:none"><label>Enter The New State: </label><input name="add_new_state" id="add_new_state" value="" type="text" class=""/></p>
		</p>

		<p id="city_p">
			<label for="city" name="city_label" id="city_label" >City</label>
			<select name="city" name="city" id="city" class="validate-select" onchange="addNewCity()">
				<option value="">Choose</option>

				<?php foreach (Mage::helper('postad')->getAttributeOptions('product_city') as $option) { ?>
					<option value="<?php echo $option['value'] ?>"><?php echo $option['label']?></option>
				<?php } ?>

				<option value="other_city"><?php echo 'other'?></label>
			</select> (Click  Other to add City)

			<p id="add_new_city_p" style="display:none"><label>Enter The New City: </label><input name="add_new_city" id="add_new_city" value="" type="text" class=""/></p>
		</p>

		<p>
			<label for="zipcode" name="zipcode_label" id="zipcode_label">Zip Code</label>
			<input type="text" name="zipcode" id="zipcode" value="" class="required-entry"/>
		</p>

		<p>
			<label for="telephone" name="telephone_label" id="telephone_label">Land Line</label>
			<input type="text" name="telephone" id="telephone" value="" class="required-entry"/>
		</p>

		<p>
			<label for="mobile_telephone" name="mobile_telephone_label" id="telephone_label">Mobile</label>
			<input type="text" name="mobile_telephone" id="mobile_telephone" value="" class="required-entry" maxlength="10"/>
		</p>

		<p>
			<label for="email" name="email_label" id="email_label">Email</label>
			<input type="text" name="email" id="email" value="" class="required-entry validate-email"/>
		</p>

		<p>
			<label for="website" name="website_label" id="website_label">Website</label>
			<input type="text" name="website" id="website" value="" class="required-entry"/>
		</p>

		<input type="hidden" id="current_url" name="current_url" value="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" />

		<p><input type="submit" name="submit" value="Submit">

	</form>
</div>

<script type="text/javascript">
//< ![CDATA[
	var myForm = new VarienForm('classified-ad-form', true);
//]]>
</script>

<script type="text/javascript">
	function addNewState()
	{
		if (jQuery("#state").val() == "other_state")	{
			jQuery("#add_new_state_p").show();

			jQuery("#add_new_state").addClass("required-entry");
		} else {
			jQuery("#add_new_state_p").hide();
			jQuery("#add_new_state").val("");

			jQuery("#add_new_state").removeClass("required-entry");
		}
	}

	function addNewCity()
	{
		if (jQuery("#city").val() == "other_city")	{
			jQuery("#add_new_city_p").show();

			jQuery("#add_new_city").addClass("required-entry");
		} else {
			jQuery("#add_new_city_p").hide();
			jQuery("#add_new_city").val("");

			jQuery("#add_new_city").removeClass("required-entry");
		}
	}

	function valueCheck()
	{
		if (jQuery("#trialperiod").val() != 'free') {
			if (jQuery("#type_of_ad").val() == '6') {

				jQuery("#expiry_months_3_div").show();
				jQuery("#expiry_months_6_div").show();
				jQuery("#expiry_months_12_div").show();

				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();
				jQuery("#serial_num").addClass('required-entry');

				jQuery("#condition").removeClass("validate-select");
				jQuery("#condition_p").hide();

				jQuery("#price_p").show();

				jQuery("#weight_p").show();
				jQuery("#model_p").show();
				jQuery("#year_p").show();

				jQuery("#hours_p").hide();
				jQuery("#hours").val("");

			} else if (jQuery("#type_of_ad").val() == '5') {

				jQuery("#expiry_months_3_div").show();

				jQuery("#expiry_months_3")
				jQuery("#expiry_months_6_div").hide();
				jQuery("#expiry_months_12_div").hide();

				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();
				jQuery("#serial_num").addClass('required-entry');

				jQuery("#condition").addClass("validate-select");
				jQuery("#condition_p").show();
			
				jQuery("#weight_p").show();
				jQuery("#model_p").show();
				jQuery("#year_p").show();

				jQuery("#price_p").show();

				jQuery("#hours_p").show();

			} else if (jQuery("#type_of_ad").val() == '4') {

				jQuery("#expiry_months_3_div").show();
				jQuery("#expiry_months_6_div").show();
				jQuery("#expiry_months_12_div").hide();

				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();
				jQuery("#serial_num").addClass('required-entry');

				jQuery("#condition_p").show();
				jQuery("#condition").addClass("validate-select");

				jQuery("#weight_p").show();
				jQuery("#model_p").show();
				jQuery("#year_p").show();

				jQuery("#price_p").hide();
				jQuery("#ad_price").val("");

				jQuery("#hours_p").show();

			} else if (jQuery("#type_of_ad").val() == '3') {

				jQuery("#make").val("");
				jQuery("#make_p").hide();
				
				jQuery("#serial_num").val("");
				jQuery("#serial_num_p").hide();	
				jQuery("#serial_num").removeClass('required-entry');

				jQuery("#condition").addClass("validate-select");
				jQuery("#condition").val("").removeClass("validate-select");
				jQuery("#condition_p").hide();

				jQuery("#weight_p").hide();

				jQuery("#model_p").hide();
				jQuery("#model").val("");

				jQuery("#year_p").hide();
				jQuery("#year").val("");

				jQuery("#expiry_months_3_div").show();
				jQuery("#expiry_months_6_div").show();
				jQuery("#expiry_months_12_div").show();

				jQuery("#price_p").hide();
				jQuery("#ad_price").val("");

				jQuery("#hours_p").hide();
				jQuery("#hours").val("");
			} else {

				jQuery("#expiry_months_3_div").hide();
				jQuery("#expiry_months_6_div").hide();
				jQuery("#expiry_months_12_div").hide();

				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();
				jQuery("#condition").addClass("validate-select");
				jQuery("#condition_p").show();
				jQuery("#weight_p").show();

				jQuery("#price_p").hide();
				jQuery("#ad_price").val("");
			}
		} else {
			if (jQuery("#type_of_ad").val() == '6') {
				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();

				jQuery("#condition").removeClass("validate-select");
				jQuery("#condition_p").hide();

				jQuery("#year_p").show();

				jQuery("#weight_p").show();
				jQuery("#model_p").show();
				jQuery("#price_p").show();

				jQuery("#hours_p").hide();
				jQuery("#hours").val("");
			} else if (jQuery("#type_of_ad").val() == '5') {
				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();

				jQuery("#condition").addClass("validate-select");
				jQuery("#condition_p").show();

				jQuery("#year_p").show();
			
				jQuery("#weight_p").show();
				jQuery("#model_p").show();
				jQuery("#price_p").show();
				jQuery("#hours_p").show();
			} else if (jQuery("#type_of_ad").val() == '4') {
				jQuery("#make_p").show();
				jQuery("#serial_num_p").show();

				jQuery("#condition_p").show();
				jQuery("#condition").addClass("validate-select");

				jQuery("#weight_p").show();
				jQuery("#model_p").show();

				jQuery("#year_p").show();

				jQuery("#price_p").hide();
				jQuery("#ad_price").val("");

				jQuery("#hours_p").show();

			} else if (jQuery("#type_of_ad").val() == '3') {
				jQuery("#make").val("");
				jQuery("#make_p").hide();
				
				jQuery("#serial_num").val("");
				jQuery("#serial_num_p").hide();	

				jQuery("#condition").addClass("validate-select");
				jQuery("#condition").val("").removeClass("validate-select");
				jQuery("#condition_p").hide();

				jQuery("#weight_p").hide();

				jQuery("#model_p").hide();
				jQuery("#model").val("");

				jQuery("#year_p").hide();
				jQuery("#year").val("");

				jQuery("#price_p").hide();
				jQuery("#ad_price").val("");

				jQuery("#hours_p").hide();
				jQuery("#hours").val("");
			}
		}
	}

	function subcategorySelect()
	{
		var value = jQuery("#category").val();

		if (value != 'other_main' ) {
			var reloadurl = '<?php echo $this->getUrl('postad/index/subcategory')?>';

			new Ajax.Request(reloadurl, {
				method: 'post',
				parameters: {
	            	categoryid : value
	        	},

	        	onComplete: function(transport) {
	        		var data = transport.responseText.evalJSON();

	        		$('sub_category').update($H(data).map(function(o){
	        			return '<option value="' + o.key + '">' + o.value + '</option>';
	        		}).join(''));

	        		Element.show('subcategory_p');
	        	}
			});
		}

		jQuery("#sub_category").removeClass("");
	}

	function categoryOtherSelect()
	{
		if ($(category).getValue() == 'other_main') {
			Element.show('category_other_p');
			Element.show('subcategory_other_p');

			$('sub_category').childElements()[0].selected=true
			
			Element.hide('subcategory_p');
		} else {
			Element.hide('category_other_p');
			Element.hide('subcategory_other_p');
		}
	}

	function subCategoryOtherSelect()
	{
		if ($(sub_category).getValue() == 'other_sub') {
			Element.show('subcategory_other_p');

			jQuery("#sub_category_other").addClass("required-entry");
		} else {
			Element.hide('subcategory_other_p');

			jQuery("#sub_category_other").removeClass("required-entry");
		}
	}

	function countrySelect()
	{
		if ($(country).getValue() == '26') {

			$(state).childElements()[0].selected=true
			Element.hide(state_p);

			Element.hide(add_new_state_p);
			Element.hide(add_new_city_p);

			jQuery("#add_new_state").val("");
			jQuery("#add_new_city").val("");

			$(city).childElements()[0].selected=true
			Element.hide(city_p);
		} else {
			Element.show(state_p);
			Element.show(city_p);
		}
	}

	function makeSelectAction()
	{
		jQuery("#make").addClass("validate-select");
		jQuery("#make").removeClass("validation-passed");
		jQuery("#make").removeClass("validation-advice");
		jQuery("#new-make").val("");
		jQuery("#new-make").removeClass("required-entry");
		jQuery(".new-make-div").hide();
	}

	function enableNewMake()
	{
		jQuery("#make").removeClass("validate-select");
		jQuery("#make").removeClass("validation-advice");
		jQuery("#new-make").addClass("required-entry");
		jQuery(".new-make-div").show();
	}

	jQuery(document).ready(function() {
		jQuery("#category").change(function() {
			if (jQuery("#category").val() == "other_main") {
				jQuery("#subcategory_p").hide();
			}
		});
	});

</script>