<form action="<?php echo $this->getClassifiedSaveUrl();?>" method="post" name="classified-ad-form" enctype="multipart/form-data">
	
	<input type="file" name="filename1" id="filename1">
	<input type="file" name="filename2" id="filename2">
	<input type="file" name="filename3" id="filename3">
	<input type="file" name="filename4" id="filename4">
	<input type="submit" name="submit" value="Submit">
</form>