<h1>Contact Us</h1>

<div class="contact-us-block">
	<div class="contact-description">
	</div>
	<div class="contact-form-block">
		<form name="contact-form" id="new-contact-form" action="<?php echo Mage::getUrl('postad/index/contactprocess')?>" method="post">
			<p>
				<label for="contact-name">Name :</label>
				<input name="contact-name" id="contact-name" value=""/>
			</p>

			<p>
				<label for="contact-email">Email : </label>
				<input name="contact-email" id="contact-email" value=""/>
			</p>

			<p>
				<label for="contact-no">Telephone :</label>
				<input name="contact-no" id="contact-no" value=""/>
			</p>

			<p>
				<label for="contact-message">Message : </label>
				<textarea id="contact-message" cols="25" rows="5" name="contact-message"></textarea>
			</p>

			<button type="submit" name="contact-submit" class="contact-submit">Submit</button>

		</form>
	</div>
	<div class="contact-address">
		
	</div>
</div>