<?php
	$collection = $collection = Mage::helper('postad')->getCraneCollection();
?>

<ul class="cranecollisting jcarousel jcarousel-skin-tango">
<?php foreach ($collection as $record) { ?>
		<li><a><?php echo $record ?></a></li>
<?php } ?>

</ul>

<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('.cranecollisting').jcarousel({
			auto: 2,
			wrap: 'last',
        	//initCallback: cranecollisting_initCallback
		});
	});

	function cranecollisting_initCallback(carousel)
	{
	    // Disable autoscrolling if the user clicks the prev or next button.
	    carousel.buttonNext.bind('click', function() {
	        carousel.startAuto(0);
	    });

	    carousel.buttonPrev.bind('click', function() {
	        carousel.startAuto(0);
	    });

	    // Pause autoscrolling if the user moves with the cursor over the clip.
	    carousel.clip.hover(function() {
	        carousel.stopAuto();
	    }, function() {
	        carousel.startAuto();
	    });
	};

</script>