<?php 
	//$manufacturerCollection = Mage::helper('postad')->getManufacturerCollection();
?>
<div class="manufacturer-listing">
	<div class="manufacturer-title"><img src="<?php echo $this->getSkinUrl("images/search_e.jpg") ?>" alt="" /></div>
	<div class="manufacturer-table">
		<div class="manufacturer-heavyequipment">
			<div class="manufacturer-heavyequipment-title">
				<span>Heavy Equipments</span>
			</div>
			<div class="heavyequipment-first-column">
				<?php  echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/heavyequipfirstcol.phtml')->toHtml(); ?>
			</div>
			<div class="heavyequipment-second-column">
				
			</div>
			<div class="heavyequipment-third-column">
				
			</div>
		</div>
		<div class="truck-crane">
			<div class="truck-title">
				<span>Trucks</span>
			</div>
			<div class="truck-column">
				
			</div>
			<div class="crane-title">
				<span>Cranes</span>
			</div>
			<div class="crane-column">
				
			</div>
		</div>
	</div>

</div>
