<?php 
	//$manufacturerCollection = Mage::helper('postad')->getManufacturerCollection();
?>
<div class="manufacturer-listing">
	<div class="manufacturer-title"><img src="<?php echo $this->getSkinUrl("images/search_e.jpg") ?>" alt="" /></div>
	<div class="manufacturer-table">
		<div class="manufacturer-heavyequipment">
			<div class="manufacturer-heavyequipment-title">
				<div class="category-title-new">Machinery Equipment</div>
			</div>
			<div class="heavyequipment-column" id="heavyequipment-first-column">
				<?php  echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/heavyequipfirstcol.phtml')->toHtml(); ?>
			</div>
		</div>
		<div class="manufacturer-truck">
			<div class="truck-title">
				<div class="category-title-new">Trucks</div>
			</div>
			<div class="truck-column">
				<?php  echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/truck-column.phtml')->toHtml(); ?>
			</div>
		</div>
		<div class="manufacturer-crane">
			<div class="crane-title">
				<div class="category-title-new">Cranes</div>
			</div>
			<div class="crane-column">
				<?php  echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/crane-column.phtml')->toHtml(); ?>
			</div>
		</div>
	</div>

</div>


