
<script type="text/javascript">

jQuery(document).ready(function() {
    jQuery('#trailercarousel').jcarousel({
        vertical: true,
        scroll: 2
    });
});

</script>

<div class="heavy jcarousel" id="jcarousel1">
<div class="heavy-title"><img src="<?php echo $this->getSkinUrl("images/trailer.jpg") ?>" alt="" /></div>
	<div id="wrap">
		<ul class="heavy-categories jcarousel jcarousel-skin-tango" id="trailercarousel">
			<?php $cat = Mage::getModel('catalog/category')->load(62);
			$subcats = $cat->getChildren();

			foreach(explode(',',$subcats) as $subCatid)
			{
			$_category = Mage::getModel('catalog/category')->load($subCatid);
			if($_category->getIsActive()) {
			echo '<li class="sub_cat">';
			echo '<a href="'.$_category->getURL().'" title="View the products for the "'.$_category->getName().'" category">'.$_category->getName().'</a>';
			}
			echo '</li>';
			}
			?>
		</ul>
	</div>
</div>