<?php
	$attributes = Mage::getSingleton('catalogsearch/advanced')->getAttributes();
?>
<?php $maxQueryLength= Mage::helper('catalogsearch')->getMaxQueryLength();?>

<form action="<?php echo $this->getAdvancedSearchPostUrl() ?>" method="get" id="new-form-validate" name="new-form-validate">
	<div class="customfieldset advanced-search">
		<ul class="form-list" id="advanced-search-list">
			<li>
				<label for="category_search_field" >Category</label>

				<select name="category" id="category_search_field">
					<option value="">-- Any Category --</option>
					<?php foreach ($this->getStoreCategories() as $_category) { ?>
						<?php if($_category->hasChildren()){ ?>
							<option class="parent-cat" value="<?php echo $_category->getId(); ?>"><?php echo $_category->getName();?></option>
							<?php foreach ($_category->getChildren() as $subcategory) { ?>
								<?php if($subcategory->getIsActive()) { ?>
									<option value="<?php echo $subcategory->getId(); ?>"<?php echo ($this->getRequest()->getQuery('category') == $subcategory->getId() ? ' selected="selected"': "") ?>>---<?php echo $subcategory->getName(); ?></option>
								<?php } ?>
							<?php } ?>
						<?php } else if ($_category->getIsActive()) {?>
							<option value="<?php echo $_category->getId(); ?>"><?php echo $_category->getName();?></option>
						<?php } ?>
					<?php } ?>
				</select>
			</li>
			<li>
				<?php foreach ($this->getSearchableAttributes() as $_attribute) { ?>
					<?php $_code = $_attribute->getAttributeCode() ?>

					<?php
						if ($_code == 'tax_class_id' || $_code == 'product_use_type') {
							continue;
						}
					?>

					<li>
						<label for="<?php echo $_code ?>"><?php echo $this->getAttributeLabel($_attribute) ?></label>
						<?php switch($this->getAttributeInputType($_attribute)) { 
							case 'number': ?>
								<div class="input-range">
									<input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
									<span class="separator">To</span>
									<input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" maxlength="<?php echo $maxQueryLength;?>" />
								</div>
							<?php break;
							case 'price': ?>
								<div class="input-range">
									<input name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" maxlength="<?php echo $maxQueryLength;?>" />
									<span class="separator">To</span>
									<input name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" maxlength="<?php echo $maxQueryLength;?>" />
									<small>(<?php echo $this->getCurrency($_attribute); ?>)</small>
								</div>
							<?php break;
							case 'select': ?>
								<div class="input-box">
									<?php echo $this->getAttributeSelectElement($_attribute) ?>
								</div>
							<?php break;
							case 'yesno': ?>
								<?php echo $this->getAttributeYesNoElement($_attribute) ?>
							<?php break;
							case 'date': ?>
								<div class="input-range">
									<?php echo $this->getDateInput($_attribute, 'from') ?>
									<span class="separator">To</span>
									<?php echo $this->getDateInput($_attribute, 'to') ?>
								</div>
							<?php break;
							default: ?>
								<div class="input-box">
									<input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>" maxlength="<?php echo $maxQueryLength;?>" />
								</div>
						<?php } ?>
					</li>
				<?php } ?>
			</li>
		</ul>
		<script type="text/javascript">decorateList('advanced-search-list')</script>
	</div>
	<!-- Sending Hidden input for Rental tab-->
	<input type="hidden" value="4" name="product_use_type[]" id="product_use_type" />
	<div class="buttons">
    	<button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('new-form-validate', true);
//]]>
</script>
